### ISSUE TITLE
Broken Link [Bug]

### ISSUE THREAD

**Issue by cadop** [NVIDIA-Omniverse/OpenUSD-Code-Samples#62]
The page: https://docs.omniverse.nvidia.com/dev-guide/latest/programmer_ref/usd/data-types/convert-vtarray-numpy.html 

Hyperlinks to a broken link: https://docs.omniverse.nvidia.com/dev-guide/latest/dev_usd/quick-start/usd-types.html

Problem is https://github.com/NVIDIA-Omniverse/OpenUSD-Code-Samples/blob/0966cb17fcf66a661cd48c061ff228cbab4c36a2/source/data-types/convert-vtarray-numpy/header.md?plain=1#L1

**Comment by apric0ts** [comment]
The [new link](https://docs.omniverse.nvidia.com/usd/latest/technical_reference/usd-types.html) for Omniverse's Data Types Documentation doesn't have documentation relating to Vt specifically, but there are separate docs for Vt: https://docs.omniverse.nvidia.com/kit/docs/pxr-usd-api/latest/pxr/Vt.html
